version: "3.8"
services:
  client:
    container_name: client
    build: ./
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 4173:4173
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: >
      sh -c "npm run build &&
             npm run preview"
